name: opus
provides: opus
license: BSD-3-Clause
license-files: [COPYING, LICENSE_PLEASE_READ.txt]
configure: [--enable-libopus]
source: { git: https://github.com/xiph/opus, ref: "v{version}" }
versions: { git-tags: '^v(\d+\.\d+(?:\.\d+)?)$' }
platforms: all
