name: highway
license: Apache-2.0 OR BSD-3-Clause
license-files: [LICENSE]
source: { git: https://github.com/google/highway, ref: "{version}" }
versions: { git-tags: '^(\d+\.\d+\.\d+)$' }
platforms: all
