#!/usr/bin/env bash
# libmp3lame (LAME): MP3 audio encoder (LGPL-2.0-or-later), static. Ported from devenvy/ffmpeg scripts/deps/libmp3lame.sh.

# LAME 3.100 exports lame_init_old in its symbol file but no longer defines it,
# which breaks the link on strict toolchains. Drop it. Use -i.bak (an explicit backup
# suffix): BSD/macOS sed requires an argument after -i, whereas GNU's bare `sed -i`
# does not — the attached-suffix form works on both. (GNU-bare `sed -i` fails on the
# macOS/iOS runners with "command i expects \ followed by text".)
sed -i.bak '/lame_init_old/d' include/libmp3lame.sym
rm -f include/libmp3lame.sym.bak

# --disable-decoder: we want LAME's ENCODER only. FFmpeg decodes MP3 with its own native
# decoder, and --enable-libmp3lame wires up the encoder alone, so LAME's decode path is dead
# weight here. It is also load-bearing from 4.0 on: LAME 4.0 dropped the bundled mpglib for an
# external libmpg123 >= 1.26.0 and its configure defaults the decoder ON, so the build died at
#   checking use of external mpg123 decoder... configure: error: no, libmpg123 not found
# across every RID and all four cells. configure only raises that when the decoder was
# explicitly requested; with it disabled it proceeds and needs no libmpg123, so this keeps a
# whole new dependency out of the ledger rather than adding one. The option is present in both
# 3.100 and 4.0 (verified in each tarball's configure), so a line that pins back still builds.
LAME_ARGS=(--prefix="${DEPS_DIR}" --disable-shared --enable-static --disable-frontend --disable-decoder --enable-nasm --with-pic)
LAME_ENV=()
[ -n "${CROSS_HOST:-}" ] && LAME_ARGS+=(--host="${CROSS_HOST}")   # cross triple resolved in 02_configure
case "${BUILD_RID}" in
  # LAME 3.100 ships a configure generated by an OLD autoconf, whose AC_HEADER_STDC uses
  # a *runtime* probe. Cross-compiling to iOS can't run it, so STDC_HEADERS stays
  # undefined and mpglib/mpg123.h falls back to `#define memcpy(d,s,n) bcopy(...)` —
  # which Xcode's clang rejects (C99). Supply the answer configure can't probe (iOS has
  # conforming STDC headers) so mpglib uses <string.h>.
  ios-arm64|ios-sim-arm64|maccatalyst-*) LAME_ENV+=(ac_cv_header_stdc=yes) ;;
esac
# Scope the cache override to configure only (via env) — don't leak it to later deps.
env "${LAME_ENV[@]+"${LAME_ENV[@]}"}" ./configure "${LAME_ARGS[@]}"
make -j"${JOBS}"
make install
